version: "3.8"
services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - celery-worker

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery-worker:
    build: .
    container_name: celery-worker
    command: celery -A tasks worker --concurrency=4 --loglevel=INFO
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  react-app:
    build:
      context: ./cv-builder-frontend
      dockerfile: Dockerfile
    container_name: react-app
    expose:
      - "80"

  nginx-proxy:
    build:
      context: ./nginx-proxy
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask-app
      - react-app

volumes:
  redis_data:
